---
#******************************************************************************
# File: test1.yml 
#******************************************************************************

- name: Configure AltLinux8
  hosts: localhost
  tasks:
  - name: Push  mnt-SAMSON.mount
    copy: 
      src: mnt-SAMSON.mount
      dest: /etc/systemd/system/
      mode: 0644
    notify: systemd daemon reloaded
    
  - name: Push  mnt-SAMSON.automount
    copy: 
      src: mnt-SAMSON.automount
      dest: /etc/systemd/system/
      mode: 0644
    notify:
    - systemd daemon reloaded
    - enabled and start mnt-SAMSON.automount
 
  - name: Push  link
    copy: 
      src: "Инструкции САМСОН.desktop"
      dest: /usr/share/Desktop/
      mode: 0744
      
