---
#******************************************************************************
# File: test1.yml
#******************************************************************************

- name: Test handlers
  hosts: localhost
  tasks:
  - name: Push  mnt-SAMSON.mount
    copy: 
      src: mnt-SAMSON.mount
      dest: /etc/systemd/system/
      mode: 0644
    notify:  add line

  handlers:
  - name: add line
    file:
      path: "/tmp/file.txt"
      state: touch
